import type { Currency, FinancialProfile } from "./types";

export const DEMO_PROFILE_TWD: FinancialProfile = {
  profile: {
    id: "demo-twd",
    name: "Demo (TWD)",
    age: 27,
    occupation: "Full-stack Engineer",
    country: "TW",
    dependentsCount: 0,
    currency: "TWD",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  personalFinance: {
    monthlyIncomeFixed: 60000,
    monthlyIncomeVariableAvg12m: 20000,
    monthlyEssentialExpense: 30000,
    monthlyNonEssentialExpense: 10000,
    emergencyFundCash: 500000,
    highInterestDebtBalance: 0,
    highInterestDebtRate: 0,
    debtMonthlyPayment: 0,
    insuranceCoverageScore: 70,
    targetLifestyleMonthlyCost: 45000,
    relocationGoalYears: 5,
  },
  investment: {
    items: [
      {
        id: "inv-0050",
        name: "0050 ETF",
        category: "equity_etf",
        marketValue: 300000,
        monthlyContribution: 10000,
        expectedReturnAnnual: 0.07,
        expectedVolatilityAnnual: 0.18,
        liquidityLevel: 5,
        concentrationRiskLevel: 2,
      },
      {
        id: "inv-cash",
        name: "Cash / 活存",
        category: "cash",
        marketValue: 200000,
        monthlyContribution: 0,
        liquidityLevel: 5,
        concentrationRiskLevel: 1,
      },
      {
        id: "inv-vt",
        name: "VT (海外)",
        category: "equity_etf",
        marketValue: 150000,
        monthlyContribution: 5000,
        expectedReturnAnnual: 0.075,
        expectedVolatilityAnnual: 0.16,
        liquidityLevel: 4,
        concentrationRiskLevel: 2,
      },
      {
        id: "inv-btc",
        name: "BTC",
        category: "crypto",
        marketValue: 80000,
        monthlyContribution: 2000,
        expectedReturnAnnual: 0.15,
        expectedVolatilityAnnual: 0.7,
        liquidityLevel: 4,
        concentrationRiskLevel: 5,
      },
    ],
    rebalancingFrequencyMonths: 6,
    maxSinglePositionRatioTarget: 0.25,
    riskTolerance: "medium",
    laborIncomeCorrelationToMarket: "high",
  },
  incomeGeneration: {
    engines: [
      {
        id: "eng-salary",
        name: "正職工程師",
        type: "salary",
        monthlyRevenueAvg6m: 60000,
        monthlyCostAvg6m: 0,
        monthlyHoursAvg6m: 160,
        growthRate6m: 0.02,
        volatility6m: 0.05,
        ownerDependencyScore: 100,
        scalabilityScore: 20,
        automationScore: 10,
        moatScore: 40,
        sixMonthPositiveNcf: true,
        ownerDependencyTrend: "flat",
      },
      {
        id: "eng-freelance",
        name: "接案開發",
        type: "freelance",
        monthlyRevenueAvg6m: 20000,
        monthlyCostAvg6m: 2000,
        monthlyHoursAvg6m: 40,
        growthRate6m: 0.1,
        volatility6m: 0.3,
        ownerDependencyScore: 90,
        scalabilityScore: 40,
        automationScore: 20,
        moatScore: 50,
        sixMonthPositiveNcf: true,
        ownerDependencyTrend: "falling",
      },
    ],
    targetPeopleSupported: 3,
    targetGeoMode: "dual_country",
    targetFinancialIndependenceYears: 15,
    entrepreneurshipIntent: true,
  },
  goals: {
    targetRetirementAge: 50,
    targetMigrationYear: 2033,
    targetBusinessLaunchYear: 2028,
    targetMonthlyCostSingle: 40000,
    targetMonthlyCostThreePeople: 90000,
    targetMonthlyCostEurope: 150000,
    semiPassiveAnnualIncome: 120000,
  },
};

export const DEMO_PROFILE_USD: FinancialProfile = {
  profile: {
    id: "demo-usd",
    name: "Demo (USD)",
    age: 30,
    occupation: "Senior Engineer",
    country: "US",
    dependentsCount: 1,
    currency: "USD",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  personalFinance: {
    monthlyIncomeFixed: 9000,
    monthlyIncomeVariableAvg12m: 1500,
    monthlyEssentialExpense: 4200,
    monthlyNonEssentialExpense: 1200,
    emergencyFundCash: 35000,
    highInterestDebtBalance: 4000,
    highInterestDebtRate: 0.18,
    debtMonthlyPayment: 250,
    insuranceCoverageScore: 80,
    targetLifestyleMonthlyCost: 6000,
    relocationGoalYears: null,
  },
  investment: {
    items: [
      {
        id: "inv-vti",
        name: "VTI",
        category: "equity_etf",
        marketValue: 80000,
        monthlyContribution: 1200,
        expectedReturnAnnual: 0.08,
        expectedVolatilityAnnual: 0.17,
        liquidityLevel: 5,
        concentrationRiskLevel: 2,
      },
      {
        id: "inv-bnd",
        name: "BND",
        category: "bond",
        marketValue: 20000,
        monthlyContribution: 300,
        expectedReturnAnnual: 0.04,
        expectedVolatilityAnnual: 0.06,
        liquidityLevel: 5,
        concentrationRiskLevel: 1,
      },
      {
        id: "inv-cash",
        name: "HYSA",
        category: "cash",
        marketValue: 15000,
        monthlyContribution: 0,
        liquidityLevel: 5,
        concentrationRiskLevel: 1,
      },
    ],
    rebalancingFrequencyMonths: 12,
    maxSinglePositionRatioTarget: 0.35,
    riskTolerance: "medium",
    laborIncomeCorrelationToMarket: "high",
  },
  incomeGeneration: {
    engines: [
      {
        id: "eng-salary",
        name: "Day Job",
        type: "salary",
        monthlyRevenueAvg6m: 9000,
        monthlyCostAvg6m: 0,
        monthlyHoursAvg6m: 160,
        growthRate6m: 0.04,
        volatility6m: 0.03,
        ownerDependencyScore: 100,
        scalabilityScore: 25,
        automationScore: 10,
        moatScore: 50,
        sixMonthPositiveNcf: true,
        ownerDependencyTrend: "flat",
      },
      {
        id: "eng-saas",
        name: "Side SaaS",
        type: "saas",
        monthlyRevenueAvg6m: 1500,
        monthlyCostAvg6m: 250,
        monthlyHoursAvg6m: 30,
        growthRate6m: 0.2,
        volatility6m: 0.15,
        ownerDependencyScore: 70,
        scalabilityScore: 80,
        automationScore: 65,
        moatScore: 55,
        sixMonthPositiveNcf: true,
        ownerDependencyTrend: "falling",
      },
    ],
    targetPeopleSupported: 3,
    targetGeoMode: "dual_country",
    targetFinancialIndependenceYears: 12,
    entrepreneurshipIntent: true,
  },
  goals: {
    targetRetirementAge: 48,
    targetMigrationYear: 2032,
    targetBusinessLaunchYear: 2027,
    targetMonthlyCostSingle: 5000,
    targetMonthlyCostThreePeople: 9000,
    targetMonthlyCostEurope: 7500,
    semiPassiveAnnualIncome: 15000,
  },
};

export function demoProfileFor(currency: Currency): FinancialProfile {
  return currency === "USD" ? DEMO_PROFILE_USD : DEMO_PROFILE_TWD;
}
